apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-frontend
  labels:
    app: mlops-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-frontend
  template:
    metadata:
      labels:
        app: mlops-frontend
    spec:
      containers:
        - name: mlops-frontend
          image: taimooranwar/mlops-frontend:latest
          ports:
            - containerPort: 80
