name: Frontend Dev

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Build the Docker image from the Frontend directory
    - name: Build Docker Image
      run: |
        docker build -t taimooranwar/mlops-frontend:latest -f Frontend/Dockerfile Frontend/
